### ISSUE TITLE
run a jupyter notebook to visualize the pdb file

### ISSUE THREAD

**Issue by ahm531** [FAIRmat-NFDI/nomad-unisyscat-plugin#30]
When following the steps for the "run a jupyter notebook to visualize the pdb file" I got the following error.

![image](https://github.com/FAIRmat-NFDI/nomad-unisyscat-plugin/assets/115071866/444dc653-e1aa-4235-9eaa-4f10f5f58779)

**Comment by schumannj** [comment]
Hmm, I guess this has something to do with the settings in the docker image. If we add this plugin to the example oasis it should work. For the local settings I am not sure in how much detail we can go here. I could add a disclaimer that for the north tools the right settings and permissions need to be set.

**Comment by schumannj** [comment]
@ahm531 was that on your local Oasis or the main example Oasis? Now that the plugin is deployed we could change the whole documentation to work on the example oasis

**Comment by ahm531** [comment]
Hi @schumannj 
This was on my local Oasis. 
I have just tried to follow the steps on the Example Oasis, and it is working.
