### ISSUE TITLE
Schema for Sample & Sample processing

### ISSUE THREAD

**Issue by schumannj** [FAIRmat-NFDI/nomad-unisyscat-plugin#4]
do we need one or should the basic sample be enough for this?

**Comment by ahm531** [comment]
I have created a simple schema in YAML to capture some quantities related to the sample. I think having these quantities in the app would be helpful? 
Protien used: ReRH or ReMBH 
Physical form: Crystal, Solution, Lyophilizate
Gas Exchange use: H2 or D2 

I have uploaded it the share NOMAD upload, and created entries for the two samples we have in hand. 
However, the entries are not identified as samples - and an error of `could not normalize section` appear. I'm working on figuring this out.

**Comment by ahm531** [comment]
A simple custom schema of samples has been created. Two entries were also created for the two samples in the Oasis example. 

The `ELNInstrument` basesection was used to instantiate the three instruments. The text was simply copied from the SI of the paper with minor modifications.

A test general sample preparation process workflow was created using the `ELNProcess` basesection.
