### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by schumannj** [FAIRmat-NFDI/nomad-unisyscat-plugin#5]
Documentation
    - Update the docs to write some How to’s
    - Tutorial:
        - Upload Gaussian simulation and share
        - Create Sample entry
        - Create Measurement entries
            - First, manually with Create form Schema for IR and NRVS
            - Secondly directly by dropping the files for the EPR
            - Showcase metadata

**Comment by schumannj** [comment]
- [ ] index file:
- [ ] How to: 
- [ ] upload samples and measurements
- [ ] upload gaussian DFT
- [ ] run a jupyter notebook to visualize the pdb file
- [ ] collaborate / add other users to project
- [ ] find entries (use the app)

**Comment by schumannj** [comment]
split how to into new issue

**Comment by ahm531** [comment]
I have just pushed a branch with my initials (AM) which includes updates to the index page with general information about the demo.
